### ISSUE TITLE
Prašymas

### ISSUE THREAD

**Issue by ignuxas** [Adomas-Alimas/EdukaScores#1]
Ar galėčiau šį ir "Eduka Explits" Repository įdėti į senų video aprašymus, ar padaryti naują video apie šį extension, parodyti kaip naudotis jūsų API atradimais, extension ir kviesti žmones prisijungti prie šio projekto?

**Comment by Adomas-Alimas** [comment]
Yep, viskas open-source ir prieinama bet kam, kas nori.
